services:
  steam-headless-holo:
    container_name: steam-headless-holo
    build:
      context: /mnt/user/appdata/docker-steam-headless-holo
      dockerfile: Dockerfile
    env_file: .env
    # environment:
    #   - PUID=${PUID}
    #   - PGID=${PGID}
    #   - UMASK=${UMASK}
    #   - USER_PASSWORD=${USER_PASSWORD}
    #   - TZ=${TZ}
    #   - USER_LOCALES=${USER_LOCALES}
    #   - NVIDIA_DRIVER_CAPABILITIES=${NVIDIA_DRIVER_CAPABILITIES}
    #   - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES}
    #   - DISPLAY=${DISPLAY}
    #   - MODE=${MODE}
    #   - WEB_UI_MODE=${WEB_UI_MODE}
    #   - ENABLE_VNC_AUDIO=${ENABLE_VNC_AUDIO}
    volumes:
      - ${APPDATA_DIR}:/home/default
      - ${GAMES_DIR}:/mnt/games
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/input:/dev/input
    ports:
      - '${PORT_NOVNC_WEB}:8083'
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    network_mode: "host"
    