---

name: Issues

on:
  issues:
    types: [labeled, unlabeled]

jobs:
  label:
    name: Label Issues
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
      pull-requests: write
    steps:
      - name: Label Issues
        uses: dessant/label-actions@65225c179d3b2502f6eda7b3d15101a3f412366b #v5.0.3
        with:
          github-token: ${{ github.token }}
